### ISSUE TITLE
Not working on kodi

### ISSUE THREAD

**Issue by Hjhghhh** [sabbiriptv/JIO_IPTV#2]
Showing error 
![Screenshot_20221225-203330](https://user-images.githubusercontent.com/117298843/209473337-5844b28d-c27e-4d5b-8454-dd81d5de6281.png)

**Comment by Viraagj** [comment]
Huge buffering issue

**Comment by Viraagj** [comment]
It's was super lame to put 

http://iamsom69.co.in/autoq.php? as I don't think this can handle all that much traffic

**Comment by sabbiriptv** [comment]
**I Will Try To Scrape (https://jiotvweb.vercel.app) Tomorrow And If It Doesn't Goes Well Then,
I Will Have No Other Choice Then Deleting This Repository 😥**

**Comment by Viraagj** [comment]
If you can do 

https://sneh-tatasky.web.app/

**Comment by sabbiriptv** [comment]
Try This And Give Me Feedback:
**https://tinyurl.com/mt2yefkt**

**Comment by Viraagj** [comment]
> Try This And Give Me Feedback: **https://tinyurl.com/mt2yefkt**

Not working on Kodi

However now your previous jio tv m3u is working smooth 

Must be lesser traffic ... Your server is now responding almost smooth

**Comment by Viraagj** [comment]
Tata sky didn't worked at all

**Comment by Viraagj** [comment]
https://bit.ly/tata001

**Comment by Viraagj** [comment]
> @sabbiriptv The TPlay M3U file is working fine on OTT Navigator App.
> 
> Also it seems the load on your Jio Server is less during morning and hence the same is also working perfectly fine

Yess but the problem is we are trying to watch Tv on TV

**Comment by nabendu1** [comment]
> > @sabbiriptv The TPlay M3U file is working fine on OTT Navigator App.
> > Also it seems the load on your Jio Server is less during morning and hence the same is also working perfectly fine
> 
> Yess but the problem is we are trying to watch Tv on TV

@Viraagj  install OTT Navigator App on your Android TV from either PlayStore or Aptoide Store if u have a Firestick . 

At least tried with Tata Play  M3U files are playing fine using OTT Navigator App on TV

**Comment by Viraagj** [comment]
I know about ott navigator
But it doesn't work properly on my firestick
Ott navigator don't even install on my firestick

**Comment by sabbiriptv** [comment]
New SERVER Added Please Check Now

**Comment by Viraagj** [comment]
> New SERVER Added Please Check Now

Updated file ?

**Comment by Viraagj** [comment]
Both are not working now 😌🐱

**Comment by sabbiriptv** [comment]
Both Are Working Fine Now **(After Update)**

**Comment by Aeropro4** [comment]
> Both Are Working Fine Now **(After Update)**

Umm @sabbiriptv the buffering has gotten worse than previous version

**Comment by Viraagj** [comment]
😅😅😅😅

**Comment by sabbiriptv** [comment]
Try NOW

**Comment by Jaysarna** [comment]
yes working now please provide me link to add in kodi IPTV add-on for your repo to make it automatic right-now i have to download it multiple time
