### ISSUE TITLE
Zip file  not found

### ISSUE THREAD

**Issue by Hanchate** [sabbiriptv/JIO_IPTV#4]
Please upload zip file,

**Comment by sabbiriptv** [comment]
https://github.com/sabbiriptv/JIO_IPTV/archive/refs/heads/main.zip

**Comment by Hanchate** [comment]
This zip file not working 
![Screenshot_2023-02-02-23-59-01-831_org xbmc kodi](https://user-images.githubusercontent.com/122559792/216416588-d86264e0-76f1-407d-87a9-9e91d4a4b2a5.jpg)
![Screenshot_2023-02-02-23-59-09-952_org xbmc kodi](https://user-images.githubusercontent.com/122559792/216416626-0c618f7b-f44a-48f4-b3b2-aae311ab5680.jpg)

**Comment by sabbiriptv** [comment]
It's Not An Addon 😐 It's Just An M3U File You Have To Use Simple IPTV
Client To Use This

**Comment by Hanchate** [comment]
Please let me know the steps to use this?
